# Generated by Django 5.2.8 on 2025-12-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photoapp', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
